### PR TITLE
Small changes to verify successful start and handle non-yes answer

### PR DESCRIPTION
**Pull request by peterroth**

### CODE REVIEW

**Comment by ps100000** [comment]
You have to add a loop around the read or else it will continue with the rest of the script even if you type an invalid answer. :)

**Comment by peterroth** [comment]
Sorry for the delay. I set a loop for starting the wireguard interface.

**Comment by ps100000** [comment]
No problem. I would say that it's fine function wise now but it seems like you messed up the indentation in the `start_wireguard`function. If you can fix this it would be ready to merge. :)

**Comment by peterroth** [comment]
Yeah, noticed that. It looks fine in vi, odd with Sublime, and even more odd on GitHub :D

**Comment by ps100000** [comment]
I guess you mixed up tabs & spaces. :D
Sorry to bother you again but could you replace line 221-241 with another call to `start_wireguard`. I somehow didn't notice yesterday that it's the same exact thing. This is the last change I promise. 😅

**Comment by peterroth** [comment]
That was my plan, but due to my (very)short memory I forgot that :S It's added now.

**Comment by ps100000** [comment]
Perfect! :)

**Pull request merged**
